# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_platform:
    path_segment_name_generator: 'App\WorldCafe\Operation\WorldCafeSegmentNameGenerator'
    enable_entrypoint: false
    enable_docs: false
    mapping:
        paths:
            - '%kernel.project_dir%/packages/Core/src/Entity'
            - '%kernel.project_dir%/packages/Core/src/Model'
            - '%kernel.project_dir%/packages/Fishbowl/src/Entity'
            - '%kernel.project_dir%/packages/WorldCafe/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    graphql:
        enabled: true
        graphql_playground:
            enabled: false
        graphiql:
            enabled: false
