# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

framework:
    messenger:
        failure_transport: failed
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            async_openai:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 15
                    delay: 4000
                    multiplier: 2

            failed: 'doctrine://default?queue_name=failed'
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            App\Fishbowl\Message\OpenAI\AskSummaryOpenAI: async_openai
            App\Fishbowl\Message\OpenAI\GetSummaryOpenAI: async_openai
