# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

twig:
    strict_variables: '%kernel.debug%'
    default_path: '%kernel.project_dir%/templates'
    exception_controller: null
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
