# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

framework:
    workflows:
        event:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentStatus'
            supports:
                - App\Fishbowl\Entity\Fishbowl
                - App\WorldCafe\Entity\WorldCafe
            initial_marking: not_started
            places:
                - not_started
                - introduction
                - running
                - conclusions
                - finished
            transitions:
                introduce:
                    from: not_started
                    to: introduction
                run:
                    from: introduction
                    to: running
                no_intro_run:
                    from: not_started
                    to: running
                finish:
                    from: running
                    to: finished
                to_conclusions:
                    from: running
                    to: conclusions
                conclude:
                    from: conclusions
                    to: finished
