name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: what-happened
      attributes:
          label: Description of the bug
          description: Explain what bug did you experienced, you can also add images.
          placeholder: Tell us what you saw!
          value: 'A bug happened!'
      validations:
          required: true
    - type: textarea
      id: what-happened
      attributes:
          label: Definition of the solution
          description: What did you expect to see instead?
          placeholder: Explain what did you expect.
      validations:
          required: true
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
