name: Feature Request
description: Request a feature for Stooa.
title: '[Feature]: '
labels: ['feature-request']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to ask for new features :tada:!
    - type: textarea
      id: feature
      attributes:
          label: 'Description of the feature'
          description: We are really excited for you to share your ideas with the community!
          placeholder: Tell us what you miss!
          value: 'A flying car!'
      validations:
          required: true
    - type: textarea
      id: idea
      attributes:
          label: 'Description of the solution'
          description: What do you think it can be done to solve this.
          placeholder: Tell usyour idea.
      validations:
          required: true
