# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Core\Controller
    type: attribute
