# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_platform:
    enable_entrypoint: true
    enable_docs: true
    graphql:
        default_ide: graphql_playground
        graphql_playground:
            enabled: true
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
