# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
            channels: ["!event", "!doctrine"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
