# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

gesdinet_jwt_refresh_token:
    path: /refresh-token
    controller: gesdinet.jwtrefreshtoken::refresh
