# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This workflow runs all the PHPUnit tests.

name: Backend tests

on:
  pull_request:

jobs:
  backend-tests:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        php: ['7.4']

    steps:
      - name: Checkout the repository to Github workspace
        uses: actions/checkout@v2

      - name: Setup the PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Add PHPUnit matcher
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Installs Composer
        uses: ramsey/composer-install@v1
        with:
          composer-options: --working-dir=backend --prefer-dist --no-scripts

      - name: Execute PHPUnit
      - run: vendor/bin/phpunit
