name: DCO Assistant

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  Signature:
    runs-on: ubuntu-latest
    steps:
      - name: DCO Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the DCO Document and I hereby sign the DCO') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: signatures/version1/dco.json
          path-to-document: https://github.com/Stooa/Stooa/blob/main/DCOLICENSE
          branch: main
          remote-organization-name: Stooa
          remote-repository-name: DCO-signatures
          use-dco-flag: true
          create-file-commit-message: 'Creating file for storing DCO Signatures'
          signed-commit-message: '$contributorName has signed the DCO in #$pullRequestNo' 
          custom-allsigned-prcomment: '**DCO Assistant** All Contributors have signed the DCO. 📝 ✅ ' 

