# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This workflow ensures that all the Javascript code is linted correctly.

name: Frontend lint

on:
  pull_request:

jobs:
  frontend-lint:
    name: Node ${{ matrix.node }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node: ['14.15']

    steps:
      - name: Checkout the repository to Github workspace
        uses: actions/checkout@v2

      - name: Setup the Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Find Yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Recover Yarn cache to speed up builds
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install all NPM dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint to ensure Javascript coding standards
        run: yarn run eslint components contexts customTypes hooks layouts lib pages ui
